# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/OREFA',
                'doc_host': 'https://florisabrams.github.io',
                'git_url': 'https://github.com/florisabrams/OREFA',
                'lib_path': 'OREFA'},
  'syms': { 'OREFA.Parcel': { 'OREFA.Parcel.Parcel': ('parcel.html#parcel', 'OREFA/Parcel.py'),
                              'OREFA.Parcel.Parcel.__init__': ('parcel.html#parcel.__init__', 'OREFA/Parcel.py'),
                              'OREFA.Parcel.Parcel.__repr__': ('parcel.html#parcel.__repr__', 'OREFA/Parcel.py'),
                              'OREFA.Parcel.Parcel.product_conc_prediction': ( 'parcel.html#parcel.product_conc_prediction',
                                                                               'OREFA/Parcel.py')},
            'OREFA.core': {'OREFA.core.foo': ('core.html#foo', 'OREFA/core.py')}}}
