# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/OREFA',
                'doc_host': 'https://florisabrams.github.io',
                'git_url': 'https://github.com/florisabrams/OREFA',
                'lib_path': 'OREFA'},
  'syms': {'OREFA.core': {'OREFA.core.foo': ('core.html#foo', 'OREFA/core.py')}}}
